#!/usr/bin/env bash
# Installs the repo's git pre-commit hook. Idempotent.
#
# Run: npm run install-hooks
#
# The hook runs typecheck + lint + format:check + tests on staged changes.
# Keeps the repo self-contained (no husky dependency).

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="${REPO_ROOT}/.git/hooks"
HOOK_FILE="${HOOK_DIR}/pre-commit"

if [ ! -d "${HOOK_DIR}" ]; then
  echo "error: ${HOOK_DIR} does not exist — is this a git repo?" >&2
  exit 1
fi

cat > "${HOOK_FILE}" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-git-hooks.sh. Re-run that script to
# reinstall. Blocks the commit if typecheck, lint, format:check, or tests
# fail on the current tree.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "[pre-commit] typecheck"
npm run -s typecheck

echo "[pre-commit] lint"
npm run -s lint

echo "[pre-commit] format:check"
npm run -s format:check

echo "[pre-commit] tests"
npm run -s test
HOOK

chmod +x "${HOOK_FILE}"
echo "installed pre-commit hook at ${HOOK_FILE}"
